# Generated by Django 2.0.4 on 2018-05-21 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20180521_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name_user',
            name='tag_line',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.name_User'),
        ),
    ]
