# Generated by Django 2.0.4 on 2018-05-22 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20180522_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('tag_line', models.CharField(max_length=255)),
                ('date_of_created', models.DateField(blank=True, null=True)),
                ('uname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='video.userProfile')),
            ],
        ),
    ]
