# Generated by Django 2.0.4 on 2018-05-22 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20180522_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='uname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='video.userProfile'),
        ),
    ]
