# Generated by Django 2.0.4 on 2018-05-23 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_of_upload',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
