# Generated by Django 2.0.4 on 2018-05-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_video_date_of_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
