# Generated by Django 2.0.4 on 2018-05-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0017_auto_20180523_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
