# Generated by Django 2.0.4 on 2018-05-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0021_auto_20180523_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name_channel',
            field=models.CharField(max_length=255),
        ),
    ]
