# Generated by Django 2.0.4 on 2018-05-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0026_auto_20180524_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Channel'),
        ),
    ]
