# Generated by Django 2.0.4 on 2018-05-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0033_video_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='uname',
        ),
        migrations.RemoveField(
            model_name='video',
            name='cat_list',
        ),
        migrations.RemoveField(
            model_name='video',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='uname',
        ),
        migrations.DeleteModel(
            name='Categorys',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
