# Generated by Django 2.0.4 on 2018-05-25 16:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0034_auto_20180525_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag_line', models.CharField(max_length=255)),
                ('img', models.FileField(upload_to='')),
                ('subsciber', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 5, 25, 22, 4, 49, 679772))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='upload')),
                ('category', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 5, 25, 22, 4, 49, 679772))),
                ('description', models.TextField(max_length=300)),
                ('views', models.IntegerField(default=0)),
                ('channel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
