# Generated by Django 2.0.4 on 2018-05-26 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0035_channel_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='img',
            field=models.FileField(upload_to='upload/img/'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 11, 51, 10, 133551)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 11, 51, 10, 133551)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
