# Generated by Django 2.0.4 on 2018-05-26 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0036_auto_20180526_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='channel_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='channel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 13, 11, 25, 277581)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 13, 11, 25, 277581)),
        ),
    ]
