# Generated by Django 2.0.4 on 2018-05-26 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0037_auto_20180526_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 13, 12, 30, 938096)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 13, 12, 30, 938096)),
        ),
    ]
