# Generated by Django 2.0.4 on 2018-05-26 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0038_auto_20180526_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='img',
            field=models.FileField(blank=True, upload_to='upload/img/'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 20, 16, 40, 734407)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 20, 16, 40, 734407)),
        ),
    ]
