# Generated by Django 2.0.4 on 2018-05-26 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0039_auto_20180526_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 20, 18, 36, 611410)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='img',
            field=models.FileField(upload_to='upload/img/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 20, 18, 36, 627010)),
        ),
    ]
