# Generated by Django 2.0.4 on 2018-05-28 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0041_auto_20180528_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='user',
        ),
        migrations.AlterField(
            model_name='channel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 23, 1, 52, 168582)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 23, 1, 52, 168582)),
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
