# Generated by Django 2.0.4 on 2018-05-28 17:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0042_auto_20180528_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='channel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 23, 4, 47, 545090)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 23, 4, 47, 545090)),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='sub_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Channel'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
