# Generated by Django 2.0.4 on 2018-05-29 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0043_auto_20180528_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videos',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 10, 53, 14, 152552)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 10, 53, 14, 168152)),
        ),
    ]
