# Generated by Django 2.0.4 on 2018-05-29 06:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0044_auto_20180529_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='channel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 12, 19, 23, 260637)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 12, 19, 23, 260637)),
        ),
        migrations.AddField(
            model_name='watch',
            name='viewsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Videos'),
        ),
    ]
